trigger:
- master
- develop
- feature/*
- hotfix/*

variables:
  ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}:
    imageName: release
    sqlconnection: $(PROD_SQL_CON)
  ${{ else }}:
    imageName: development
    sqlconnection: $(TEST_SQL_CON)

stages:
- stage:
  displayName: 'Deploy to test environment'
  jobs:
    - job:
      displayName: 'Build and deploy'
      steps:
        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: login
            containerRegistry: allbertCommonRegistryConnection
        - task: Bash@3
          displayName: 'Echo sql connection string'
          inputs:
            targetType: 'inline'
            script: echo '${{variables.sqlconnection}}'
        - task: Docker@2
          displayName: 'Build docker image'
          inputs:
            command: 'build'
            repository: 'allbertapi'
            Dockerfile: '**/Dockerfile'
            tags: |
              ${{variables.imageName}}.v.$(Build.BuildId)
              ${{variables.imageName}}
            arguments: '--build-arg SQLCONNECTION="${{variables.sqlconnection}}"'
        - task: Docker@2
          displayName: 'Push docker image'
          inputs:
            containerRegistry: 'allbertCommonRegistryConnection'
            repository: 'allbertapi'
            command: 'push'
            tags: |
              ${{variables.imageName}}.v.$(Build.BuildId)
              ${{variables.imageName}}
