using System;
using System.Reflection;
[assembly: System.Reflection.AssemblyCompanyAttribute("AllbertBackend.API")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("AllbertBackend.API")]
[assembly: System.Reflection.AssemblyTitleAttribute("AllbertBackend.API")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
